= REST API Guide
양성빈;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 5
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 메서드 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[auth]]
= 인증

[[signup]]
== 회원가입

[[collect-member-info]]
=== 기본 정보 수집

`POST` 요청을 사용해서 회원의 기본정보를 수집할 수 있다.

operation::collect-member-info[snippets='request-fields,curl-request,http-request,request-headers,http-response,response-headers,response-fields,links']

[[verify-code]]
=== 인증번호 확인

`POST` 요청을 사용해서 인증코드를 확인할 수 있다.

operation::verify-code[snippets='request-fields,curl-request,http-request,request-headers,query-parameters,http-response,response-headers,response-fields,links']

[[resend-code]]
=== 인증번호 재전송

`POST` 요청을 사용해서 인증번호를 재전송 할 수 있다.

operation::resend-code[snippets='curl-request,http-request,request-headers,query-parameters,http-response,response-headers,response-fields,links']

[[setup-password]]
=== 비밀번호 설정

`POST` 요청을 사용해서 비밀번호를 설정할 수 있다.

operation::setup-password[snippets='request-fields,curl-request,http-request,request-headers,query-parameters,http-response,response-headers,response-fields,links']